binary_sensor:
  # Состояния каналов
  - platform: modbus_controller
    modbus_controller_id: wb_led_1
    id: state_ch1
    register_type: coil
    address: 0
    bitmask: 1
    internal: true
    on_state:
      then:
        - lambda: |-
            bool new_state = id(state_ch1).state;
            if (id(channel_1_state) != new_state) {
              id(channel_1_state) = new_state;
              if (new_state) {
                if (!id(light_ch1).current_values.is_on()) {
                  id(light_ch1).turn_on().perform();
                }
              } else {
                if (id(light_ch1).current_values.is_on()) {
                  id(light_ch1).turn_off().perform();
                }
              }
            }

  - platform: modbus_controller
    modbus_controller_id: wb_led_1
    id: state_ch2
    register_type: coil
    address: 1
    bitmask: 1
    internal: true
    on_state:
      then:
        - lambda: |-
            bool new_state = id(state_ch2).state;
            if (id(channel_2_state) != new_state) {
              id(channel_2_state) = new_state;
              if (new_state) {
                if (!id(light_ch2).current_values.is_on()) {
                  id(light_ch2).turn_on().perform();
                }
              } else {
                if (id(light_ch2).current_values.is_on()) {
                  id(light_ch2).turn_off().perform();
                }
              }
            }

  - platform: modbus_controller
    modbus_controller_id: wb_led_1
    id: state_ch3
    register_type: coil
    address: 2
    bitmask: 1
    internal: true
    on_state:
      then:
        - lambda: |-
            bool new_state = id(state_ch3).state;
            if (id(channel_3_state) != new_state) {
              id(channel_3_state) = new_state;
              if (new_state) {
                if (!id(light_ch3).current_values.is_on()) {
                  id(light_ch3).turn_on().perform();
                }
              } else {
                if (id(light_ch3).current_values.is_on()) {
                  id(light_ch3).turn_off().perform();
                }
              }
            }

  - platform: modbus_controller
    modbus_controller_id: wb_led_1
    id: state_ch4
    register_type: coil
    address: 3
    bitmask: 1
    internal: true
    on_state:
      then:
        - lambda: |-
            bool new_state = id(state_ch4).state;
            if (id(channel_4_state) != new_state) {
              id(channel_4_state) = new_state;
              if (new_state) {
                if (!id(light_ch4).current_values.is_on()) {
                  id(light_ch4).turn_on().perform();
                }
              } else {
                if (id(light_ch4).current_values.is_on()) {
                  id(light_ch4).turn_off().perform();
                }
              }
            }

  # События: двойное нажатие
  - platform: template
    id: double_press_event_ch1
    name: "Ch1 Double Press"
    internal: false
    on_press:
      - delay: 100ms
      - binary_sensor.template.publish:
          id: double_press_event_ch1
          state: false

  - platform: template
    id: double_press_event_ch2
    name: "Ch2 Double Press"
    internal: false
    on_press:
      - delay: 100ms
      - binary_sensor.template.publish:
          id: double_press_event_ch2
          state: false

  - platform: template
    id: double_press_event_ch3
    name: "Ch3 Double Press"
    internal: false
    on_press:
      - delay: 100ms
      - binary_sensor.template.publish:
          id: double_press_event_ch3
          state: false

  - platform: template
    id: double_press_event_ch4
    name: "Ch4 Double Press"
    internal: false
    on_press:
      - delay: 100ms
      - binary_sensor.template.publish:
          id: double_press_event_ch4
          state: false

  # События: коротко + долгое нажатие
  - platform: template
    id: short_long_press_event_ch1
    name: "Ch1 Short+Long Press"
    internal: false
    on_press:
      - delay: 100ms
      - binary_sensor.template.publish:
          id: short_long_press_event_ch1
          state: false

  - platform: template
    id: short_long_press_event_ch2
    name: "Ch2 Short+Long Press"
    internal: false
    on_press:
      - delay: 100ms
      - binary_sensor.template.publish:
          id: short_long_press_event_ch2
          state: false

  - platform: template
    id: short_long_press_event_ch3
    name: "Ch3 Short+Long Press"
    internal: false
    on_press:
      - delay: 100ms
      - binary_sensor.template.publish:
          id: short_long_press_event_ch3
          state: false

  - platform: template
    id: short_long_press_event_ch4
    name: "Ch4 Short+Long Press"
    internal: false
    on_press:
      - delay: 100ms
      - binary_sensor.template.publish:
          id: short_long_press_event_ch4
          state: false
