binary_sensor:
  # Состояния каналов wb1
  - platform: modbus_controller
    modbus_controller_id: wb1
    id: state_sens_wb1_ch1
    register_type: coil
    address: {{ 0 + reg }}
    bitmask: 1
    internal: true
    on_state:
      then:
        - lambda: |-
            bool new_state = id(state_sens_wb1_ch1).state;
            if (id(state_wb1_ch1) != new_state) {
              id(state_wb1_ch1) = new_state;
              if (new_state) {
                if (!id(light_wb1_ch1).current_values.is_on()) {
                  id(light_wb1_ch1).turn_on().perform();
                }
              } else {
                if (id(light_wb1_ch1).current_values.is_on()) {
                  id(light_wb1_ch1).turn_off().perform();
                }
              }
            }

  # События: двойное нажатие wb1
  - platform: template
    id: double_press_event_wb1_ch1
    name: "wb1_ch1 Double Press"
    internal: false
    on_press:
      - delay: 100ms
      - binary_sensor.template.publish:
          id: double_press_event_wb1_ch1
          state: false

  # События: коротко + долгое нажатие wb1
  - platform: template
    id: short_long_press_event_wb1_ch1
    name: "wb1_ch1 Short+Long Press"
    internal: false
    on_press:
      - delay: 100ms
      - binary_sensor.template.publish:
          id: short_long_press_event_wb1_ch1
          state: false

