binary_sensor:
# --- физические кнопки ---
  - platform: gpio
    id: gpio0_btn
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
    internal: true
    filters:
      - invert:
      - delayed_on: ${debounce_on}
      - delayed_off: ${debounce_off}
    on_multi_click:
      # --- одиночное нажатие ---
      - timing:
          - ON for at most ${single_max}
          - OFF for at least ${single_off}
        then:
          - logger.log: "Single click"
          - binary_sensor.template.publish:
              id: single_click_btn
              state: true
          - script.execute: single_click_reset_btn

      # --- длинное нажатие ---
      - timing:
          - ON for at least ${long_min}
        then:
          - logger.log: "Long click"
          - binary_sensor.template.publish:
              id: long_click_btn
              state: true
          - script.execute: long_click_reset_btn

      # --- двойное нажатие ---
      - timing:
          - ON for at most ${double_on}
          - OFF for at most ${double_off}
          - ON for at most ${double_on}
        then:
          - logger.log: "Double click"
          - binary_sensor.template.publish:
              id: double_click_btn
              state: true
          - script.execute: double_click_reset_btn

      # --- короткое + длинное ---
      - timing:
          - ON for at most ${shortlong_on}
          - OFF for at most ${shortlong_off}
          - ON for at least ${shortlong_long}
        then:
          - logger.log: "Short + Long click"
          - binary_sensor.template.publish:
              id: short_long_click_btn
              state: true
          - script.execute: short_long_click_reset_btn

  # --- виртуальные сенсоры для HA ---
  - platform: template
    id: single_click_btn
    name: "Single Click btn"

  - platform: template
    id: long_click_btn
    name: "Long Click btn"

  - platform: template
    id: double_click_btn
    name: "Double Click btn"

  - platform: template
    id: short_long_click_btn
    name: "Short + Long Click btn"
