substitutions:
  name: wb-led-esp32
  friendly_name: "wb-led"

  baud_rate: 115200
  update_interval: "800ms"
  command_throttle: "60ms"

  pulse_time: "300ms"
  debounce_on: "10ms"
  debounce_off: "10ms"
  single_max: "500ms"
  single_off: "300ms"
  long_min: "800ms"
  double_on: "400ms"
  double_off: "300ms"
  shortlong_on: "500ms"
  shortlong_off: "300ms"
  shortlong_long: "800ms"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Настройка UART
uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: ${baud_rate}
  stop_bits: 2

# Настройка Modbus
modbus:
  id: modbus_rs_485
  flow_control_pin: GPIO4  # DE/RE объединены на один пин

modbus_controller:
  - id: wb1
    address: 128
    modbus_id: modbus_rs_485
    update_interval: ${update_interval}
    command_throttle: ${command_throttle}

  - id: wb2
    address: 129
    modbus_id: modbus_rs_485
    update_interval: ${update_interval}
    command_throttle: ${command_throttle}

  - id: wb3
    address: 115
    modbus_id: modbus_rs_485
    update_interval: ${update_interval}
    command_throttle: ${command_throttle}
